country = ['monaco', 'italia', 'golandia', 'portugalia', 'france']
print('Отсортированный')
print(sorted(country))
print('исходный')
print(country)
print('обратный')
country.reverse()
print(country)
print('ещё обратный')
country.reverse()
print(country)
